### ISSUE TITLE
All enderchest contents empty on server restart

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ColoredEnderChests#4]
## Description (Required)
All items are cleared from all of the color ender chests on the server after every restart of the server.

## Steps to reproduce the Issue (Required)
Place items in any color enderchest.  Revisit that color enderchest after the server restart to see the items be magically gone.

## Expected behavior (Required)
Contents should stay in tact between restarts. 

## Server Log / Error Report
Nothing by way of errors coming up on this.

## Environment (Required)
[09:37:09 INFO]: Paper v1_14_R1 (Paper #173)
[09:37:09 INFO]:
[09:37:09 INFO]: CS-CoreLib vDEV - 64 (git 9091bb0b)
[09:37:09 INFO]: Slimefun vDEV - 135 (git f54fd125)
[09:37:09 INFO]:
[09:37:09 INFO]: Installed Addons (8)
[09:37:09 INFO]:  Barrels vDEV - 2 (git 847bc83b)
[09:37:09 INFO]:  ExtraGear vDEV - 3 (git de222ab7)
[09:37:09 INFO]:  ChestTerminal v1.0
[09:37:09 INFO]:  HotbarPets vDEV - 10 (git 7d790905)
[09:37:09 INFO]:  ExoticGarden vDEV - 17 (git 122f5555)
[09:37:09 INFO]:  SoulJars vDEV - 3 (git ebabf39f)
[09:37:09 INFO]:  ElectricSpawners vDEV - 2 (git 49ffa319)
[09:37:09 INFO]:  ColoredEnderChests vDEV - 4 (git 2ce8ec8d)

**Comment by TheBusyBiscuit** [comment]
Should be fixed in Slimefun.

**Comment by mrcoffee1026** [comment]
Still present in later build 151 with Colored Enderchest update (6):
 Paper v1_14_R1 (173)

 CS-CoreLib vDEV - 68 (git d7071a19)
 Slimefun vDEV - 151 (git 0fad51e2)

 Installed Addons (8)
  Barrels vDEV - 2 (git 847bc83b)
  ExtraGear vDEV - 3 (git de222ab7)
  ChestTerminal v1.0
  HotbarPets vDEV - 10 (git 7d790905)
  ExoticGarden vDEV - 17 (git 122f5555)
  SoulJars vDEV - 3 (git ebabf39f)
  ElectricSpawners vDEV - 2 (git 49ffa319)
  ColoredEnderChests vDEV - 6 (git 6e80c4ba)
